env:
  browser: true
  es6: true
  node: true
extends: "plugin:react/recommended"
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - "@typescript-eslint"
  - "@emotion"
rules:
  {
    "react/prop-types": 0,
    "react/no-unknown-property": ["error", { "ignore": ["css"] }],
  }
