name: Build/release

on:
  push:
    tags:
      - "v*"
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4
        # remember to keep this in sync with package.json's volta->node setting
        with:
          node-version: 20
          cache: "yarn" # I always get 'yarn cache is not found' but ah well

      - name: Build Electron app
        uses: coparse-inc/action-electron-builder@v1.0.0
        env:
          in_github_action: "true"
        with:
          github_token: ${{ secrets.github_token }}
          release: false

      - name: Sign installer
        if: github.event_name != 'pull_request'
        uses: sillsdev/codesign/trusted-signing-action@v3
        with:
          credentials: ${{ secrets.TRUSTED_SIGNING_CREDENTIALS }}
          files-folder: output
          files-folder-filter: BloomPUB*.exe
          description: "BloomPUB Viewer Installer"
          description-url: "https://bloomlibrary.org/bloompub-viewer"

      - name: Create Release
        if: github.event_name != 'pull_request'
        uses: softprops/action-gh-release@v2
        with:
          files: output/BloomPUB*.exe
          name: ${{ github.ref_name }}
          body: |
            Release for version ${{ github.ref_name }}
          draft: true
